### ISSUE TITLE
using ./update_client.sh

### ISSUE THREAD

**Issue by Mudary** [SRWieZ/php-starlink-client#8]
# System Details Report
---

## Report details
- **Date generated:**                              2024-12-20 13:52:29

## Hardware Information:
- **Hardware Model:**                              Acer Aspire TC-605
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i3-4130 × 4
- **Graphics:**                                    Intel® HD Graphics 4400 (HSW GT2)
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            P11-B4
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.8.0-51-generic

NOT using a docker program

mudary1@mudary1:~/php-starlink-client$ ./update_client.sh
  → Retrieving protoset file from your Starlink 
SpaceX.API.Device.Device is a service:
service Device {
  rpc Handle ( .SpaceX.API.Device.Request ) returns ( .SpaceX.API.Device.Response );
  rpc Stream ( stream .SpaceX.API.Device.ToDevice ) returns ( stream .SpaceX.API.Device.FromDevice );
}
  → Converting protoset to proto 
PHP Fatal error:  Uncaught Error: Call to undefined method Google\Protobuf\DescriptorPool::addMessage() in /home/mudary1/php-starlink-client/vendor/google/protobuf/src/GPBMetadata/Google/Protobuf/Internal/Descriptor.php:17
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/google/protobuf/src/Google/Protobuf/Internal/FileDescriptorSet.php(36): GPBMetadata\Google\Protobuf\Internal\Descriptor::initOnce()
#1 /home/mudary1/php-starlink-client/vendor/srwiez/grpc-protoset/src/ProtosetConverter.php(35): Google\Protobuf\Internal\FileDescriptorSet->__construct()
#2 /home/mudary1/php-starlink-client/vendor/srwiez/grpc-protoset/cli/converter.php(44): SRWieZ\GrpcProtoset\ProtosetConverter->convertProtoset()
#3 /home/mudary1/php-starlink-client/vendor/srwiez/grpc-protoset/bin/protoset-converter(6): require('...')
#4 /home/mudary1/php-starlink-client/vendor/bin/protoset-converter(119): include('...')
#5 {main}
  thrown in /home/mudary1/php-starlink-client/vendor/google/protobuf/src/GPBMetadata/Google/Protobuf/Internal/Descriptor.php on line 17

**Comment by SRWieZ** [comment]
Try reinstalling your dependencies 

```bash
rm -rf vendor/
composer install 
```

If it is still not working, please provide additional information: 
- `php -v`
- `php -m | grep grpc`
-  `composer -V`
- `composer show "google/*" --format=json`

**Comment by Mudary** [comment]
php -v
PHP 8.3.6 (cli) (built: Dec  2 2024 12:36:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
php -m | grep grpc
grpc

composer -V
Composer version 2.7.1 2024-02-09 15:26:28

composer show "google/*" --format=json
{
    "installed": [
        {
            "name": "google/protobuf",
            "direct-dependency": true,
            "homepage": "https://developers.google.com/protocol-buffers/",
            "source": "https://github.com/protocolbuffers/protobuf-php/tree/v4.29.2",
            "version": "v4.29.2",
            "description": "proto library for PHP",
            "abandoned": false
        }
    ]
}

terminal: php -S 192.168.1.20:8000 starlink.php

#!/usr/bin/env php

 []


I have never did anything with php, I'm thinking its something I did but what I don't know.
Thank you

**Comment by SRWieZ** [comment]
It's not a common error, never saw this before.

Try `composer self-update && composer update`
then retry `./update_client.sh`

By the way, you don't really need to update the client. It's already up to date. You can just use it.

**Comment by Mudary** [comment]
What directory are the file folder assets and update_client.sh suppost to be, right now  /home/mudary1/php-starlink-client

folder, maybe if I move it into the /var/www folder it should work. I use firefox as a browser..

**Comment by Mudary** [comment]
mudary1@mudary1:~/php-starlink-client/cli$ php -S 192.168.1.20:8000 index.php
[Sun Dec 22 11:57:01 2024] PHP 8.3.6 Development Server (http://192.168.1.20:8000) started
[Sun Dec 22 11:57:23 2024] 192.168.1.3:32280 Accepted

   Whoops\Exception\ErrorException 

  imagepng(assets/obstruction_map.png): Failed to open stream: No such file or directory

  at /home/mudary1/php-starlink-client/src/ObstructionMapGenerator.php:256
[Sun Dec 22 11:57:23 2024] PHP Fatal error:  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 [internal function]: Whoops\Run->handleException()
#9 {main}
  thrown in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php on line 182

   Whoops\Exception\ErrorException 

  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 [internal function]: Whoops\Run->handleException()
#9 {main}
  thrown

  at /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
[Sun Dec 22 11:57:23 2024] PHP Fatal error:  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(482): Whoops\Run->handleException()
#9 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(510): Whoops\Run->handleError()
#10 [internal function]: Whoops\Run->handleShutdown()
#11 {main}
  thrown in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php on line 182
[Sun Dec 22 11:57:23 2024] 192.168.1.3:32280 Closing
[Sun Dec 22 11:57:23 2024] 192.168.1.3:32282 Accepted

   Whoops\Exception\ErrorException 

  imagepng(assets/obstruction_map.png): Failed to open stream: No such file or directory

  at /home/mudary1/php-starlink-client/src/ObstructionMapGenerator.php:256
[Sun Dec 22 11:57:24 2024] PHP Fatal error:  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 [internal function]: Whoops\Run->handleException()
#9 {main}
  thrown in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php on line 182

   Whoops\Exception\ErrorException 

  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 [internal function]: Whoops\Run->handleException()
#9 {main}
  thrown

  at /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
[Sun Dec 22 11:57:24 2024] PHP Fatal error:  Uncaught Error: Undefined constant "NunoMaduro\Collision\STDOUT" in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php:182
Stack trace:
#0 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php(86): NunoMaduro\Collision\ConsoleColor->isSupported()
#1 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(241): NunoMaduro\Collision\ConsoleColor->apply()
#2 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(120): NunoMaduro\Collision\Highlighter->colorLines()
#3 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet()
#4 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight()
#5 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor()
#6 /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write()
#7 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle()
#8 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(482): Whoops\Run->handleException()
#9 /home/mudary1/php-starlink-client/vendor/filp/whoops/src/Whoops/Run.php(510): Whoops\Run->handleError()
#10 [internal function]: Whoops\Run->handleShutdown()
#11 {main}
  thrown in /home/mudary1/php-starlink-client/vendor/nunomaduro/collision/src/ConsoleColor.php on line 182
[Sun Dec 22 11:57:24 2024] 192.168.1.3:32282 Closing

**Comment by SRWieZ** [comment]
What are you trying to achieve? This is a library, not a website you can view in a browser.

**Comment by Mudary** [comment]
I thought this was a web page to view my starlink status. Sorry, go ahead and close.

**Comment by SRWieZ** [comment]
I'm making a desktop app right now, would you be interested?

**Comment by Mudary** [comment]
Yes please

**Comment by SRWieZ** [comment]
Almost ready! You can see it here: https://dishypilot.com
